import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  style: ["italic", "normal"],
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["devanagari", "latin"],
});

export const metadata = {
  title: "Weather app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
